// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using musicBank.Data;

#nullable disable

namespace musicBank.Migrations
{
    [DbContext(typeof(MusicBankContext))]
    partial class MusicBankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("musicBank.Models.Albums", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MumberOfSongs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Rented")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("musicBank.Models.Artists", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("musicBank.Models.Relation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlbumID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Albumsid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Artistsid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("Albumsid");

                    b.HasIndex("Artistsid");

                    b.ToTable("Relation");
                });

            modelBuilder.Entity("musicBank.Models.Relation", b =>
                {
                    b.HasOne("musicBank.Models.Albums", "Albums")
                        .WithMany("Relation")
                        .HasForeignKey("Albumsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("musicBank.Models.Artists", "Artists")
                        .WithMany()
                        .HasForeignKey("Artistsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Albums");

                    b.Navigation("Artists");
                });

            modelBuilder.Entity("musicBank.Models.Albums", b =>
                {
                    b.Navigation("Relation");
                });
#pragma warning restore 612, 618
        }
    }
}
