GET http://localhost:3000/courses

###

GET http://localhost:3000/courses

###

GET http://localhost:3000/courses/619ca99aa1506d3c53d1dab5

###

POST http://localhost:3000/courses
Content-Type: application/json

{
    "code":         "GD008G",
    "name":         "Typografi och form för webb",
    "progression":  "A",
    "semester":     "HT20",
    "syllabus":     "https://www.miun.se/utbildning/kursplaner-och-utbildningsplaner/Sok-kursplan/kursplan/?kursplanid=24399"
}


###

DELETE http://localhost:3000/courses/619cc9b018aecaccd5b8162c

###

PATCH http://localhost:3000/courses/619bd34d0eadb32ef39aa03e
Content-Type: application/json

{
        "code":         "DT071G",
        "name":         "Programmering i C#.NET",
        "progression":  "B",
        "semester":     "HT21",
        "syllabus":     "https://www.miun.se/utbildning/kursplaner-och-utbildningsplaner/Sok-kursplan/kursplan/?kursplanid=25557"
}